config/routes.rb
OpenIDTest::Application.routes.draw do
	match '/contact', :to => 'pages#contact'
	match '/about',   :to => 'pages#about'

	devise_for :users

	root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
# Schema version: 20110408140226
#
# Table name: users
#
#  id           :integer         not null, primary key
#  identity_url :string(255)
#  fullname     :string(255)
#  email        :string(255)
#  gender       :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	devise :openid_authenticatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :identity_url, :fullname, :email, :gender

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :identity_url, :presence => true
	validates :email, :format => { :with => email_regex } #, :presence => true
	def self.build_from_identity_url(identity_url)
		User.new(:identity_url => identity_url)
	end

	def self.openid_required_fields
		["fullname", "email"]
	end

	def self.openid_optional_fields
		["gender"]
	end

	def openid_fields=(fields)
		fields.each do |key, value|
		# Some AX providers can return multiple values per key
			if value.is_a? Array
			value = value.first
			end

			case key.to_s
			when "fullname"
				self.fullname = value
			when "email"
				self.email = value
			when "gender"
				self.gender = value
			else
			logger.error "Unknown OpenID field: #{key}"
			end
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Return a title on a per-page basis.
	def title
		base_title = "OpenIDTest"
		if @title.nil?
		base_title
		else
			"#{base_title} > #{@title}"
		end
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<ul>
			<% if user_signed_in? %>
			<li>
				<%= "You're signed in as #{current_user.fullname} <#{current_user.email}>" %>
			</li>
			<% else %>
			<li>
				<%= "Test your OpenID by signing in!"%>
			</li>
			<% end %>
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<% if user_signed_in? %>
			<li>
				<%= link_to "Sign out", destroy_user_session_path %>
			</li>
			<% else %>
			<li>
				<%= link_to "Sign in", new_user_session_path %>
			</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag :defaults %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
				<%= content_tag(:div, value, :class => "flash #{key}") %>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1><%= @title %></h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>OpenIDTest</h1>
<p>Welcome to OpenIDTest!</p>